# EKF configuration for map frame
# Fuses GPS (via navsat_transform) + IMU to estimate map->odom transform

ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # GPS odometry (converted by navsat_transform)
    odom0: /odometry/gps
    odom0_config: [true,  true,  true,      # x, y, z position
                   false, false, false,     # roll, pitch, yaw
                   false, false, false,     # x_dot, y_dot, z_dot
                   false, false, false,     # roll_dot, pitch_dot, yaw_dot
                   false, false, false]     # x_ddot, y_ddot, z_ddot
    odom0_queue_size: 10
    odom0_differential: false
    odom0_relative: false

    # IMU data
    imu0: /ouster/imu
    imu0_config: [false, false, false,      # x, y, z position
                  true,  true,  true,       # roll, pitch, yaw
                  false, false, false,      # x_dot, y_dot, z_dot
                  true,  true,  true,       # roll_dot, pitch_dot, yaw_dot
                  true,  true,  true]       # x_ddot, y_ddot, z_ddot
    imu0_differential: false
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    use_control: false

    # Process noise covariance [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
    process_noise_covariance: [0.05, 0.05, 0.06, 0.03, 0.03, 0.06, 0.025, 0.025, 0.04, 0.01, 0.01, 0.02, 0.01, 0.01, 0.015]

    initial_estimate_covariance: [1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9, 1e-9]
