# Navsat transform configuration
# Converts GPS fix to odometry in map frame

frequency: 30
delay: 0.0
magnetic_declination_radians: 0.0  # Set based on your location
yaw_offset: 0.0                    # Set if IMU has offset from ENU
zero_altitude: false
broadcast_utm_transform: false      # We use map frame, not UTM
broadcast_utm_transform_as_parent_frame: false
publish_filtered_gps: false
use_odometry_yaw: false            # Use IMU for yaw (6-axis IMU, no magnetometer)
wait_for_datum: false
datum: [35.84617083648474, 127.13446738445664, 100.0]  # Your Gazebo spawn location
