# Navsat transform configuration
# Converts GPS fix to odometry in map frame

navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.0  # Set based on your location
    yaw_offset: 0.0                    # Set if IMU has offset from ENU
    zero_altitude: false
    broadcast_utm_transform: false      # We use map frame, not UTM
    broadcast_utm_transform_as_parent_frame: false
    publish_filtered_gps: false
    use_odometry_yaw: true             # Use yaw from /odometry/filtered (EKF output)
    wait_for_datum: false
    datum: []                          # Auto-set from first GPS fix
