obstacle_range: 5.0
raytrace_range: 6.0

footprint: [[-0.5, -0.4], [-0.5, 0.4], [0.5, 0.4], [0.5, -0.4]]
robot_radius: 0.64

inflation_radius: 0.8
cost_scaling_factor: 10.0

observation_sources: laser_scan_sensor

laser_scan_sensor:
  sensor_frame: os_lidar
  data_type: LaserScan
  topic: /scan
  marking: true
  clearing: true
  min_obstacle_height: -0.5
  max_obstacle_height: 2.0
