# ============================================================
# Costmap 공통 파라미터
# @25_Jairlab/husky_dwa_navigation/config/ 값을 기반으로 수정됨
# ============================================================

# Husky A200 매뉴얼 기준 로봇 크기 설정
footprint: [[-0.495, -0.335], [-0.495, 0.335], [0.495, 0.335], [0.495, -0.335]]
footprint_padding: 0.01

# Transform 간 허용되는 최대 시간 지연 (초)
transform_tolerance: 1.0

# 25_Jairlab의 ObstacleLayer 설정을 따름
obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true,
            obstacle_range: 50.0,
            raytrace_range: 55.0,
            observation_persistence: 0}

# 25_Jairlab의 InflationLayer 설정을 따름
inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 4.0

# 아래 파라미터들은 25_Jairlab 설정에 따라 각 레이어 네임스페이스 내부나
# 개별 costmap 파일에서 관리되거나, ObstacleLayer 사용으로 불필요해짐.
# map_type: voxel
# obstacle_range: 30.0
# raytrace_range: 35.0
# max_obstacle_height: 2.0
# observation_sources: laser_scan_sensor
# lethal_cost_threshold: 100