# Costmap 공통 파라미터 (Global & Local)

# 로봇 footprint (Husky 크기)
footprint: [[-0.495, -0.335], [-0.495, 0.335], [0.495, 0.335], [0.495, -0.335]]

# Obstacle Layer 설정
obstacle_layer:
  enabled: true

  # LaserScan 관찰 소스
  observation_sources: scan

  scan:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    min_obstacle_height: -0.5
    max_obstacle_height: 2.0
    obstacle_range: 50.0
    raytrace_range: 55.0
    inf_is_valid: true

# Inflation Layer 설정
inflation_layer:
  enabled: true
  inflation_radius: 0.1
  cost_scaling_factor: 5.0
