DWAPlannerROS:
  # 로봇 구성 (Husky 스펙 기반)
  acc_lim_x: 2.5          # 선속도 가속도 제한 (m/s^2)
  acc_lim_y: 0.0          # Differential drive는 y 방향 이동 없음
  acc_lim_theta: 2.5      # 각속도 가속도 제한 (rad/s^2)

  # 속도 제한
  max_vel_x: 8.0          # 최대 선속도 (m/s)
  min_vel_x: -1.0         # 최소 선속도 (후진)
  max_vel_y: 0.0          # Differential drive
  min_vel_y: 0.0
  max_vel_trans: 8.0      # 최대 병진 속도
  min_vel_trans: 0.1      # 최소 병진 속도 (정지 방지)
  max_vel_theta: 1.2      # 최대 회전 속도 (rad/s)
  min_vel_theta: 0.08     # 최소 회전 속도 (rad/s)

  # 목표 허용 오차
  xy_goal_tolerance: 0.5        # 위치 허용 오차 (m)
  yaw_goal_tolerance: 3.14      # 방향 허용 오차 (rad)
  latch_xy_goal_tolerance: false

  # 경로 추종 가중치
  path_distance_bias: 32.0      # 글로벌 경로 따라가기 가중치
  goal_distance_bias: 32.0      # 목표 지점 도달 가중치
  occdist_scale: 0.02           # 장애물 회피 가중치

  # Trajectory 샘플링
  vx_samples: 10          # 선속도 샘플 개수
  vy_samples: 0           # Differential drive
  vtheta_samples: 20      # 회전속도 샘플 개수

  # Forward simulation
  sim_time: 4.0           # 미래 궤적 시뮬레이션 시간 (초) - 큰 회전 반경 허용
  sim_granularity: 0.05   # 시뮬레이션 간격 (초)
  forward_point_distance: 0.5   # 로봇 중심에서 제어 포인트까지 거리 (m)

  # 로봇 행동 설정
  stop_time_buffer: 0.2          # 정지 시 시간 버퍼
  oscillation_reset_dist: 0.1    # Oscillation 리셋 거리 (m)
  penalize_negative_x: false     # 후진 패널티 비활성화
  scaling_speed: 0.1             # 속도 스케일링 임계값 (m/s)
  max_scaling_factor: 0.5        # 최대 스케일링 팩터

  # 디버깅
  publish_traj_pc: true
  publish_cost_grid_pc: true
  global_frame_id: map
