# ============================================================
# Global Planner 파라미터
# @25_Jairlab/husky_dwa_navigation/config/ 값을 기반으로 수정됨
# ============================================================

GlobalPlanner:
  # ===== 알고리즘 및 동작 설정 =====
  allow_unknown: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false

  # ===== 목표 및 창 설정 =====
  default_tolerance: 0.0
  planner_window_x: 0.0
  planner_window_y: 0.0

  # ===== 비용 함수 설정 =====
  cost_factor: 10.0
  neutral_cost: 20
  lethal_cost: 253

  # ===== 발행 및 디버깅 설정 =====
  publish_potential: false
  planner_costmap_publish_frequency: 0.0
  publish_scale: 100