# ============================================================
# Local Costmap 파라미터
# @25_Jairlab/husky_dwa_navigation/config/ 값을 기반으로 수정됨
# ============================================================

local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 10.0
  publish_frequency: 10.0

  static_map: false
  rolling_window: true
  width: 50.0
  height: 50.0
  resolution: 0.05
  transform_tolerance: 0.5

  # 25_Jairlab 파라미터 추가
  reset_distance: 2.5
  track_unknown_space: false

  # 25_Jairlab 설정에 따라 VoxelLayer를 ObstacleLayer로 변경
  plugins:
    - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}