local_costmap:
  global_frame: utm_local
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 10
  static_map: false
  rolling_window: true
  width: 25.0  
  height: 25.0
  resolution: 0.05
  transform_tolerance: 0.2
  reset_distance: 0.25
  track_unknown_space: false


  plugins:
    - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  # plugins:
  #   - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
  #   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}