shutdown_costmaps: false
controller_frequency: 10.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0     # 진동 감지 시간 (초)
oscillation_distance: 0.5    # 진동 감지 거리 (m) - launch 파일에서 이동
oscillation_reset_dist: 0.5  # 진동 리셋 거리 (m)
recovery_behavior_enabled: true
clearing_rotation_allowed: true
conservative_clear_costmap: true  # launch 파일에서 이동



# 복구 동작 설정
recovery_behaviors:
  - name: conservative_reset
    type: clear_costmap_recovery/ClearCostmapRecovery

# rotate_recovery를 완전히 비활성화
rotate_recovery:
  enabled: false


# 복구 동작 파라미터
clear_costmap_recovery:
  reset_distance: 0.5
  layer_names: ["voxel_layer"]