# =============================================================================
# 경로 계획 파라미터 설정
# DWA 알고리즘의 경로 평가 및 궤적 생성 관련 설정
# =============================================================================

DWAPlannerROS:
  # ==========================================================================
  # 경로 평가 가중치 설정 (부드러운 움직임을 위한 가중치 조정)
  # 디퍼렌셜 드라이브 진동 최소화를 위한 최적화
  # ==========================================================================
  path_distance_bias: 32.0      # 글로벌 경로 따르기 가중치 - 추가 감소로 큰 회전 반경 허용
  goal_distance_bias: 32.0      # 목표점 도달 가중치 - 균형 잡힌 가중치로 유연성 증대
  occdist_scale: 0.02           # 장애물 회피 가중치 - 약간 증가로 안전성 유지
  forward_point_distance: 0.5   # 로봇 앞쪽 참조점 거리 (m) - 더 먼 미래 예측으로 경로 계획 개선
  
  # ==========================================================================
  # 궤적 시뮬레이션 설정 (DWA 알고리즘의 핵심 파라미터)
  # ==========================================================================
  sim_time: 4.0           # 경로 시뮬레이션 시간 (s) - 더 긴 예측으로 큰 회전 반경 계획
  sim_granularity: 0.05   # 시뮬레이션 단계 크기 (m) - 계산 비용 절약으로 예측 거리 증대
  vx_samples: 10          # x 속도 샘플 수 - 간소화로 큰 회전 중심
  vy_samples: 0           # y 속도 샘플 수 (비홀로노믹 로봇이므로 0) - 옆으로 이동 불가
  vth_samples: 20         # 회전 속도 샘플 수 - 적절한 수준으로 큰 회전 가능
  
  # ==========================================================================
  # 제어 주기 설정
  # ==========================================================================
  controller_frequency: 10.0  # 컨트롤러 주기 (Hz) - 1초에 몇 번 궤적을 계산할지
  
  # ==========================================================================
  # 시각화 설정 (디버깅 및 모니터링용)
  # ==========================================================================
  publish_traj_pc: true        # 궤적 포인트 클라우드 발행 - RViz에서 후보 궤적들 확인 가능
  publish_cost_grid_pc: true   # 비용 그리드 발행 - 각 궤적의 비용 시각화
  global_frame_id: utm_local   # 전역 프레임 ID - 좌표계 설정

# =============================================================================
# Move Base 일반 설정 (네비게이션 시스템 전반적인 동작 제어)
# =============================================================================

# ==========================================================================
# 제어 주기 설정 (시스템 반응 속도)
# ==========================================================================
planner_frequency: 5.0       # 글로벌 플래너 실행 주기 (Hz) - 전체 경로 재계산 빈도
controller_patience: 15.0    # 로컬 플래너 대기 시간 (s) - 이 시간 내에 유효한 명령이 없으면 복구 시작
planner_patience: 5.0        # 글로벌 플래너 대기 시간 (s) - 경로 계획 실패 시 복구까지 대기 시간

# ==========================================================================
# 진동 감지 및 복구 설정 (큰 회전 반경 허용)
# ==========================================================================
oscillation_timeout: 30.0     # 진동 감지 시간 (초) - 더 긴 시간으로 큰 회전 허용
oscillation_distance: 2.0     # 진동 감지 거리 (m) - 더 넓은 범위로 큰 회전 허용
recovery_behavior_enabled: false   # 복구 동작 비활성화 - 제자리 회전 방지
clearing_rotation_allowed: false   # 코스트맵 클리어링 시 회전 비허용 - 제자리 회전 완전 방지
conservative_clear_costmap: false  # 비보수적 코스트맵 클리어링 - 더 유연한 경로 허용

# ==========================================================================
# 플래너 설정 (사용할 알고리즘 지정)
# ==========================================================================
base_local_planner: dwa_local_planner/DWAPlannerROS  # 로컬 플래너 - 장애물 회피 및 즉각적인 경로 수정
base_global_planner: global_planner/GlobalPlanner   # 글로벌 플래너 - 전체 경로 계획

# =============================================================================
# Global Planner 설정 (전체 경로 계획 알고리즘 세부 설정)
# =============================================================================

GlobalPlanner:
  # ==========================================================================
  # 경로 계획 알고리즘 설정
  # ==========================================================================
  allow_unknown: true           # 미지의 영역 통과 허용 - 맵에 없는 구역도 지나갈 수 있음
  use_dijkstra: true            # 다익스트라 알고리즘 사용 - 최단 경로 보장
  use_quadratic: true           # 2차 근사 사용 - 더 부드러운 경로 생성
  use_grid_path: false          # 그리드 경로 사용 안함 - 대각선 이동 허용
  old_navfn_behavior: false     # 구형 navfn 동작 사용 안함 - 개선된 알고리즘 사용

  # ==========================================================================
  # 플래너 윈도우 설정 (경로 계획 영역 제한)
  # ==========================================================================
  planner_window_x: 0.0         # 플래너 윈도우 X축 크기 (0=전체 맵 사용)
  planner_window_y: 0.0         # 플래너 윈도우 Y축 크기 (0=전체 맵 사용)
  default_tolerance: 0.0        # 기본 허용 오차 (더 정확한 경로 계획)

  # ==========================================================================
  # 발행 및 디버깅 설정
  # ==========================================================================
  publish_scale: 100            # 발행 스케일 (경로 세밀도 향상)
  planner_costmap_publish_frequency: 0.0  # 비용맵 발행 주기
  publish_potential: false      # 포텐셜 필드 발행 비활성화 (성능 향상)

  # ==========================================================================
  # 비용 함수 설정 (gazebo_dwa 현재 설정과 동일)
  # ==========================================================================
  cost_factor: 10.0             # 현재값: 장애물 비용 가중치 - 강화된 장애물 회피
  neutral_cost: 20              # 현재값: 자유 공간 기본 비용 - 비용 차이 극대화
  lethal_cost: 253              # 기본값: 치명적 장애물 비용