# =============================================================================
# 로봇 동역학 파라미터 설정
# Husky A200 사양에 맞는 속도 및 가속도 제한 설정
# =============================================================================

DWAPlannerROS:
  # ==========================================================================
  # 속도 제한 설정 (로봇의 물리적 한계 정의)
  # ==========================================================================
  max_vel_x: 1.0      # 최대 전진 속도 (m/s) - 로봇이 낼 수 있는 최고 속도
  min_vel_x: -1.0     # 최소 전진 속도 (m/s) - 후진 시 최대 속도 (음수)
  max_vel_y: 0.0      # 최대 Y축 속도 (비홀로노믹 로봇이므로 0) - 옆으로 이동 불가
  min_vel_y: 0.0      # 최소 Y축 속도 (비홀로노믹 로봇이므로 0) - 옆으로 이동 불가
  max_vel_trans: 1.0  # 최대 이동 속도 (m/s) - 실제 사용할 최대 속도 제한
  min_vel_trans: 0.1  # 최소 이동 속도 (m/s) - 너무 느린 움직임 방지
  max_vel_theta: 0.8  # 최대 회전 속도 (rad/s) - 제자리 회전 시 최대 각속도
  min_vel_theta: 0.08 # 최소 회전 속도 (rad/s) - 너무 느린 회전 방지
  
  # ==========================================================================
  # 가속도 제한 설정 (디퍼렌셜 드라이브 진동 최소화)
  # ==========================================================================
  acc_lim_x: 2.5      # X축 가속도 제한 (m/s^2) - 부드러운 전진/후진
  acc_lim_y: 0.0      # Y축 가속도 제한 (m/s^2) - 비홀로노믹 로봇이므로 0
  acc_lim_theta: 2.5  # 회전 가속도 제한 (rad/s^2) - 진동 감소를 위한 적절한 가속도
  
  # ==========================================================================
  # 목표 도달 허용치 (언제 목표에 도달했다고 판단할지)
  # ==========================================================================
  xy_goal_tolerance: 0.5        # 위치 허용 오차 (m) - 더 정밀한 도달 요구로 큰 회전 반경 허용
  yaw_goal_tolerance: 3.14      # 방향 허용 오차 (rad) - gazebo_dwa와 동일한 설정
  latch_xy_goal_tolerance: false # 위치 도달 후 이동 허용 - 큰 회전 반경으로 목표 접근 가능
  
  # ==========================================================================
  # 로봇 행동 설정 (움직임 특성 조정)
  # ==========================================================================
  penalize_negative_x: false  # 후진 패널티 비활성화 - 전진/후진 모두 허용으로 유연성 증대
  
  # ==========================================================================
  # 안전 설정 (충돌 방지 및 안전한 정지)
  # ==========================================================================
  stop_time_buffer: 0.2       # 정지 시간 버퍼 (s) - 장애물 감지 시 안전하게 정지하기 위한 여유 시간
  scaling_speed: 0.1          # 속도 스케일링 임계값 (m/s) - 낮은 속도에서만 반경 축소
  max_scaling_factor: 0.5     # 최대 스케일링 팩터 - 더 큰 회전 반경 허용
  
  # ==========================================================================
  # 진동 방지 (같은 지점에서 계속 맴도는 현상 방지)
  # ==========================================================================
  oscillation_reset_dist: 0.1 # 진동 감지 거리 (m) - 이 거리 내에서 왔다갔다 하면 진동으로 판단하여 리셋